// export const API_END_POINT = "http://localhost:8000/api/user"
// export const API_END_POINT_CarOwner = "http://localhost:8000/api/carOwner"
// export const API_END_POINT_admin = "http://localhost:8000/api/admin"
// export const API_END_POINT_booking = "http://localhost:8000/api/booking"
// export const API_END_POINT_checkout = "http://localhost:8000"

export const API_END_POINT = "https://car-rental-ufci.onrender.com/api/user"
export const API_END_POINT_CarOwner = "https://car-rental-ufci.onrender.com/api/carOwner"
export const API_END_POINT_admin = "https://car-rental-ufci.onrender.com/api/admin"
export const API_END_POINT_booking = "https://car-rental-ufci.onrender.com/api/booking"
export const API_END_POINT_checkout= "https://car-rental-ufci.onrender.com"