name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        working-directory: server

      - name: Run Tests
        run: npm run test
        working-directory: server
